### ISSUE TITLE
Is SDF Face Shadow only affected by light direction?

### ISSUE THREAD

**Issue by Reuben-Sun** [DeJhon-Huang/FernNPR#32]
I am working at main branch. I find that the SDF Face Shadow seem to only be affected by direction of the light. When I rotate the light direction, the shadow rotate beautifully. But when I rotate the face, the shadow don't rotate with it. Is there a way to rotate the shadow while rotating the character?
![faceSDF](https://github.com/FernRP/FernRPExample/assets/61135584/08ae7b8e-7b23-4467-be1c-be2e0c6b45e3)

**Comment by DeJhon-Huang** [comment]
I've fixed this on the main branch, check out this commit:

https://github.com/FernRP/FernRP/commit/6e8d67fb40d93982cd5a7c3c6fc4a39160fd38a5

However, there is still a problem: if you use SkinMeshRender, the model's orientation will be affected by the bones, I will provide SkinMeshRender support later!
